#

name: CI-pushtomaster

on: 
 push:
  branches:
    - main
jobs:
  test-push:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Print starting message
      run: echo "hotfix commited"
    
  deploy:
  
    runs-on: ubuntu-latest
    needs: [test-push]
    steps:
    
    - name: Print Deploying
      run: echo "hotfix deployed"
